export const USERNAME_PATTERN = /^[a-zA-Z0-9_-]{4,12}$/ // 用户名正则，4到12位（字母，数字，下划线，减号）
export const USERNAME_NO_SPECIAL_PATTERN = /^[a-zA-Z0-9]{6,12}$/ // 用户名正则，4到12位（字母，数字）
export const PASSWORD_PATTERN = /^.*(?=.{6,})(?=.*\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[!@#$%^&*? ]).*$/ // 密码强度正则，最少6位，包括至少1个大写字母，1个小写字母，1个数字，1个特殊字符
export const PASSWORD_SIMPLE_PATTERN = /^[a-zA-Z0-9]{6,12}$/ // 简单密码正则
export const POS_INT_PATTERN = /^\d+$/ // 正整数正则
export const NEG_INT_PATTERN = /^-\d+$/ // 负整数正则
export const INT_PATTERN = /^-?\d+$/ // 整数正则
export const POS_PATTERN = /^\d*\.?\d+$/ // 正数正则
export const NEG_PATTERN = /^-\d*\.?\d+$/ // 负数正则
export const NUM_PATTERN = /^-?\d*\.?\d+$/ // 数字正则
export const EMAIL_PATTERN = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/ // Email正则
export const MOBILE_PATTERN = /^1[34578]\d{9}$/ // 手机号正则
export const ID_PATTERN = /^[1-9]\d{5}(18|19|([23]\d))\d{2}((0[1-9])|(10|11|12))(([0-2][1-9])|10|20|30|31)\d{3}[0-9Xx]$/ // 身份证号正则
export const URL_PATTERN = /^((https?|ftp|file):\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/ // URL正则
export const IP_PATTERN = /^((?:(?:25[0-5]|2[0-4]\d|(?:1\d{2}|[1-9]?\d))\.){3}(?:25[0-5]|2[0-4]\d|(?:1\d{2}|[1-9]?\d)))$/ // IP地址正则
export const COLOR_PATTERN = /^#?([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$/ // 十六进制颜色正则
export const QQ_PATTERN = /^[1-9][0-9]{4,10}$/ // QQ号码正则
export const WX_PATTERN = /^[a-zA-Z]([-_a-zA-Z0-9]{5,19})+$/ // 微信号正则
export const CN_PATTERN = /[\u4E00-\u9FA5]/ // 包含中文正则
